### PR TITLE
Added dist to gitignore since it's built

### PR DESCRIPTION
**Pull request by philspitler**

### CODE REVIEW

**Comment by philspitler** [comment]
Please have a look at this @joelip

**Comment by joelip** [comment]
@philspitler if you add `dist` to get ignore then apps don't work on heroku

**Comment by philspitler** [comment]
Does this currently have the ability to deploy to Heroku?  I don't see where it does.

**Comment by philspitler** [comment]
I removed a comment because it was incorrect.  Please leave this PR open while I look at something though.  Thanks!

**Comment by joelip** [comment]
:+1:

**Comment by philspitler** [comment]
Essentially it's fixed by building on heroku (which is what we should be doing).  I've done it tons of times, I just have to grab dinner so I can't do it right now.  Are you OK with adding the grunt stuff to the dependencies instead of the dev dependencies?  I believe this is a caveat of having it build there.  Then I add a script for

```javascript
"ponstinstall": "./node_modules/grunt-cli/bin/grunt build"
```

to the package.json file.

**Comment by joelip** [comment]
Maybe we're having a misunderstanding. Last I checked (which admittedly, has been maybe a month or so) Heroku takes into account the `.gitignore` when they're building files. Running `grunt build` will put everything in `dist`, the folder where our server looks to get the files it's serving up. If we put `dist` in `.gitignore`, then when someone visits the site and hits a Heroku server, there will be an error where none of the files are found because Heroku is ignoring the `dist` directory.

**Comment by joelip** [comment]
The concern isn't about Heroku not _building_ the files, it's about Heroku following the `.gitignore` and not finding the files required for the site to be served up.

**Comment by joelip** [comment]
I already had this issue with the [base project (see the commit here)](https://github.com/Bloc/base-frontend-project/commit/f39b16c60afa846b82f776be2376d86d81e8803d). This is what I'm trying to prevent.

**Comment by philspitler** [comment]
Ah, well I believe this would be the way to go then @joelip:

https://github.com/robwierzbowski/grunt-build-control

Build folders should not be in git.  It makes commits in dev NASTY.  If I have to create a complete workaround for it myself, I will.  I just had someone who ran the server in master.  Then checked out a branch, made some changes and tried to merge into master and there were conflicts in dist.

This is a fixable problem.  That said, this server is overkill for what we're trying to teach in the Angular project.  Please see https://github.com/philspitler/spa-host/blob/master/README.md.  It's ZERO build.  I can throw this command with the correct arguments in the dist directory and it just works.  So all the building stuff just goes away.  With a minor modification to allow spa-host to run on different ports (hard-coded atm).

There is a solution for either the startup project deploy to heroku without including dist director or to use spa-host.  Since we're not teaching about minification/ugification etc. because it's a FE course, I don't believe we need a whole build process and framework, IMO.

**Comment by joelip** [comment]
Hey @philspitler, we haven't had anyone else complain about build conflicts, so I'm hesitant to make a change for one instance, but I can see that it might be a problem in the future. If you want to make a PR that includes `grunt-build-control`, I'd be totally for it.

I am however, against including SPA host. Not because you aren't a great developer and I wouldn't trust something you built :smile:, but because I don't want added maintenance costs to dependencies. The server in this repo is already set up, _has all of our curriculum and documentation written around it_, and has been working fine for 99% of cases I've heard of to date. Changing it would be a huge headache and soliciting help from you to fix anything wrong with SPA host (including the fact that not all projects are SPAs — we have documentation for static sites, too) would be, too. In addition, students are much more likely to be using/seeing custom server code in their jobs than using SPA host, so I think that it would be unrepresentative of a post-Bloc experience as well.

Happy to review any PR you want to submit, or revisit this sometime in a few weeks on my own. Also, if you do submit a PR, please use a branch and don't submit directly to master. Thanks again for taking the time to work this out!

**Comment by jolip** [comment]
Guys, could you please take me off this thread. You've CC'ed jolip instead
of joelip.

Thanks,
Joanna

**Comment by philspitler** [comment]
Sorry about that @jolip!  You should be able to unsubscribe on the right side of the Github interface.  Again... My apologies.

**Pull request closed without merging**
